### ISSUE TITLE
font size for box

### ISSUE THREAD

**Issue by carol-rowe666** [pearselab/r-intro-carol-rowe666#1]
Can not get my text to center in box for question 10 because I can not get mono font. Wasting too much time for something so trivial....but would really like to know.

**Comment by willpearse** [comment]
More than reasonable!!!

I think you can change the font of the console here (https://support.rstudio.com/hc/en-us/articles/200549016-Customizing-RStudio#appearance) - I admit I don't use RStudio, so hadn't considered this problem. It must be annoying, sorry!...
